In [2]:
import numpy as np 
import scipy.stats as sp 

# 1. Test sur la moyenne d'une loi normale

### Q1

In [3]:
#code
def TestStudent(L,alpha):
    n=len(L)
    Z=np.sqrt(n)*np.abs(np.mean(L))/np.var(L,ddof=1)
    return(Z>sp.t.ppf(1-alpha/2,n-1))
    #if Z>sp.t.ppf(1-alpha/2,n-1):
        #return False
    #else:
        #return True

 ### Q2

In [4]:
#test
mu, sigma = 0, 1 
L= np.random.normal(mu, sigma, 50)
alpha=0.01
TestStudent(L,alpha)
#on ne rejette pas H_0

False

In [5]:
L= np.random.normal(1,1, 50)
TestStudent(L,alpha)
#on rejette H_0

True

### Q3

In [6]:
#alpha=0.05
z=[TestStudent(np.random.normal(0,1,50),0.05) for i in np.arange(1000)]
print("On a", 1000 - np.sum(z), "fois l'hypothèse qui est acceptée et ", np.sum(z), "fois rejettée." )

On a 932 fois l'hypothèse qui est acceptée et  68 fois rejettée.


In [6]:
#alpha=0.01
z=[TestStudent(np.random.normal(0,1,50),0.01) for i in np.arange(1000)]
print("On a", 1000 - np.sum(z), "fois l'hypothèse qui est acceptée et ", np.sum(z), "fois rejettée." )

On a 983 fois l'hypothèse qui est acceptée et  17 fois rejettée.


### Q4

In [7]:
def PValeurStudent(L):
    n=len(L)
    Z=np.sqrt(n)*np.abs(np.mean(L))/np.var(L,ddof=1)
    p=2 - 2*sp.t.cdf(Z,n-1,0,1)
    print("La p-valeur de notre test de Student est", p) 

### Q5

In [9]:
z= np.random.normal(0,1, 50)
print(PValeurStudent(z))
print(sp.ttest_1samp(z,0))

La p-valeur de notre test de Student est 0.333377527399197
None
Ttest_1sampResult(statistic=-0.8689814143255308, pvalue=0.3890939123726398)


### Q6 

In [10]:
dat=np.load("HeartRate.npy")

$H_0$ : Il n'y a pas de différences entre fréquence cardiaque avant et après une course $\newline$
$H_1$: Il y a pas de différence 

In [10]:
dat

array([[ 71, 132],
       [ 64, 156],
       [ 72, 138],
       ...,
       [ 58, 166],
       [ 66, 164],
       [ 70, 158]])

In [11]:
repos = dat[:,0]
course = dat[:,1]
diff = course - repos

In [12]:
len(diff)

800

In [13]:
TestStudent(diff,0.01)

True

In [14]:
TestStudent(diff,0.05)

True

Donc on rejette $H_0$ aux risques 0.01 et 0.05 , on peut donc dire qu'il y a une différence significative de la fréquence cardiaque avant et après une course à pied. 

# Test du chi2 d'adéquation 

## Exemple du loto 

In [12]:
Loto = np.load("Loto.npy")

### Q1

$H_0$ : Toutes les boules ont une probabilité égale d'être tirées $\newline$
$H_1$: Les boules n'ont pas une probabilité égale d'être tirées 

### Q2

In [13]:
Loto

array([710, 681, 674, 720, 702, 707, 722, 675, 676, 683, 672, 670, 682,
       670, 692, 730, 658, 687, 704, 695, 685, 669, 679, 682, 681, 687,
       704, 680, 652, 716, 716, 700, 661, 745, 719, 730, 703, 726, 722,
       694, 689, 703, 686, 692, 736, 709, 666, 675, 689], dtype=int64)

In [14]:
val_att = np.full((49,), (7*4858)/49)

chi2 = 0
for i in range(49):
    chi2 = chi2 + ((Loto[i] - val_att[i])**2)/val_att[i]

print("La statistique que l'on a calculée nous renvoie",chi2)

La statistique que l'on a calculée nous renvoie 33.19884726224783


In [17]:
sp.chisquare(Loto)

Power_divergenceResult(statistic=33.198847262247845, pvalue=0.9486238047722398)

### Q3

La stastique à pour loi asymptotique sous H0 une loi du chi2 à 48 degré de liberté$\newline$
le quantile de niveau 0.95 de la loi correspondante est :

In [18]:
sp.chi2.ppf(0.95,48, loc=0, scale=1)


65.17076890356982

### Q4

In [51]:
chi2 > sp.chi2.ppf(0.95,48, loc=0, scale=1)

False

Notre statistique est inférieure au quantile d'ordre 0.95 de la loi du chi2 à 48 degré de liberté, donc on ne rejette pas l'hypothèse H0 et on peut dire que l'on suit une loi uniforme et donc que la probabilité de tirer chaque boule est bien égale.

## La loi de Benford

In [19]:
France=np.load("France.npy")

### Q1

In [20]:
def premier_chiffre(L):
    n = len(L)
    A = []
    for i in range(n):
        A.append(int(str(L[i])[0]))
    return A
    

chiffre_sign = np.array(premier_chiffre(France)).astype(int)
prop = (np.unique(chiffre_sign, return_counts= True)[1])/10000
print("Nos propotions d'appartition de chaque chiffre sont" ,prop)

Nos propotions d'appartition de chaque chiffre sont [0.3024 0.1764 0.1279 0.0939 0.0814 0.0671 0.057  0.0504 0.0435]


### Q2

In [21]:
B = []
for i in range(1, 10):
    B.append(np.log10(1+(1/i)))

B = np.array(B)

In [22]:
B

array([0.30103   , 0.17609126, 0.12493874, 0.09691001, 0.07918125,
       0.06694679, 0.05799195, 0.05115252, 0.04575749])

### Q3

In [24]:
chi2_2 = 0
for i in range(9):
    chi2_2 = chi2_2 + ((prop[i] - B[i])**2)/B[i]

print("La statistique que l'on a calculée nous renvoie",chi2_2)

sp.chisquare(prop, B)

La statistique que l'on a calculée nous renvoie 0.00037239003373248155


Power_divergenceResult(statistic=0.00037239003373248155, pvalue=1.0)

On trouve bien la même statistique que la fonction fournie.

### Q4

In [64]:
sp.chi2.ppf(0.95,8, loc=0, scale=1)

15.50731305586545

In [65]:
chi2_2 > sp.chi2.ppf(0.95,8, loc=0, scale=1) 

False

Ainsi notre statistique est inférieure au quantile d'ordre 0.95 de la loi du chi2 à 8 degrés de liberté, donc on ne rejette pas l'hypothèse H0 et on peut dire que la loi de notre jeu de données suit bien une loi de Benford.

# Test du chi 2 d'indépendance 
## 3.1 Cancer de l'oesophage
### Q1

H0 : La loi de la consommation d'alcool quotidienne et la loi de la présence cancer sont indépendantes.$\newline$
H1 : Elles ne sont pas indépendantes. 

### Q2

In [69]:
np.array([[29, 386, 415], [75, 280, 355], [51, 87, 138], [45, 22, 67], [200, 775, 975]])

array([[ 29, 386, 415],
       [ 75, 280, 355],
       [ 51,  87, 138],
       [ 45,  22,  67],
       [200, 775, 975]])

In [75]:
Cancer = np.array([[29, 386, 415], [75, 280, 355], [51, 87, 138], [45, 22, 67], [200, 775, 975]])

chi2_3 = 0
for i in range(4):
    for j in range(2):
        chi2_3 = chi2_3 + ((Cancer[i, j]- (Cancer[4,j]*Cancer[i,2])/Cancer[4,2])**2)/((Cancer[4,j]*Cancer[i,2])/Cancer[4,2])
print(chi2_3)        

158.95457113567429


In [77]:
sp.chi2_contingency(Cancer)[0]

158.9545711356743

Notre fonction nous a bien renvoyé la même statistique que la fonction fournie.

### Q3

Sous H0, notre statistique à pour un loi asymptotique un chi2 à $(4-1)*(1-1)= 3$ ddl

In [78]:

chi2_3 > sp.chi2.ppf(0.95,3, loc=0, scale=1)

True

Notre statistique est supérieure au quantile d'ordre 0.95 de la loi du chi2 à 3 ddl, donc on rejette H0 et on peut dire que la consommation quotidienne d'alcool est liée à la présence d'un cancer chez un individu.

### Q4

H0 : La loi de la consommation de tabac quotidienne et la loi de la présence cancer sont indépendantes.$\newline$
H1 : Elles ne sont pas indépendantes.

In [80]:
Cancer2 = np.array([[78, 447, 525], [58, 178, 236], [33, 99, 132], [31, 51, 82], [200, 775, 975]])

In [81]:
chi2_4 = 0
for i in range(4):
    for j in range(2):
        chi2_4 = chi2_4 + ((Cancer2[i, j]- (Cancer2[4,j]*Cancer2[i,2])/Cancer2[4,2])**2)/((Cancer2[4,j]*Cancer2[i,2])/Cancer2[4,2])
print(chi2_4)

29.35701656004785


In [83]:
sp.chi2_contingency(Cancer2)[0]

29.35701656004785

In [85]:
chi2_4 > sp.chi2.ppf(0.95,3, loc=0, scale=1)

True

Notre statistique est suupérieure au quantile de la loi du chi2 à 3 ddl, donc on rejette H_0 et on peut dire que la consommation de tabac quotidienne est liée à la présence d'un cancer chez un individu.

### Q5

In [87]:
sp.chi2_contingency(Cancer)[1]

2.6456045978342372e-30

In [86]:
sp.chi2_contingency(Cancer2)[1]

0.0002744470597839162

In [88]:
sp.chi2_contingency(Cancer)[1] < sp.chi2_contingency(Cancer2)[1]

True

La p-value du premier test est bien inférieure à celle de la seconde, donc la dépendance de l'alcool est plus forte que celle du tabac.

## 3.2 Couleur des cheveux  VS couleur des yeux

### Q1

In [89]:
def Chi2Indep(M,alpha):
    m,n=M.shape
    t=[]
    for i in np.arange(0,m):
        for j in range(n):
            x=np.sum(M[i,:])*np.sum(M[:,j]) / np.sum(M)
            t.append(((M[i,j]-x)**2)/x)
    v=np.sum(t)
    h=sp.chi2.ppf(1-alpha,(n-1)*(m-1), loc=0, scale=1)
    return v < h

In [90]:
Chi2Indep(Cancer,0.05)

False

In [91]:
Chi2Indep(Cancer2,0.05)

False

In [93]:
F=np.array([[2,41,9],[14,95,34],[7,23,7],[8,9,64]])

In [94]:
H=np.array([[3,42,11],[15,78,50],[7,17,10],[8,8,30]])

In [95]:
Chi2Indep(F,0.05)

False

In [96]:
Chi2Indep(H,0.05)

False

In [100]:
SexeYeux = np.array([[33,31,64],[145,168,313],[101,114,215],[282,313,592]])
Chi2Indep(SexeYeux, 0.05)

True

In [98]:
SexeCheveux = np.array([[56,52,108],[143,143,286],[34,37,71],[46,81,127],[279,313,592]])
Chi2Indep(SexeCheveux,0.05)

True

In [101]:
YeuxCheveux = np.array([[5,83,20,108],[29,173,84,286],[14,40,17,71],[16,17,94,127],[64,313,215,592]])
Chi2Indep(YeuxCheveux, 0.05)

False

Ainsi, on peut voir que l'on accepte H0 pour les deux premiers tests, ce qui veut dire qu'il y aurait une indépendance entre la couleur des yeux et le sexe et la couleur des cheveux et le sexe. En revanche, on rejette H0 lors du dernier test, ce qui veut dire qu'il y aurait un lien entre la couleur des yeux et des celle des cheveux.